# os.makedirs(os.path.join(os.getcwd(),"maunish\\dave\\abcd"))
# os.chdir("desktop")
os.path.abspath("doing boring stuff with python")
os.path.isabs(os.getcwd())
# os.chdir("..\\")
os.path.relpath("doing boring stuff with python")
os.path.relpath("c:\\Users\\Maunish dave\\desktop\\doning boring stuff with python","c:\\Users")
# os.chdir("desktop\\doing boring stuff with python")
print(os.path.dirname(os.getcwd()))
print(os.path.basename(os.getcwd()))
print(os.path.split(os.getcwd()))
path = os.getcwd()
path.split(os.path.sep)
print(os.path.getsize(os.getcwd()))
print(os.listdir(os.getcwd()))
